language: csharp
solution: TonNurako.sln

install:
    - sudo apt-get -qq update
    - sudo apt-get -qq install libmotif-dev libxmu-dev libxt-dev libfontconfig1-dev xvfb fonts-ipafont-gothic xfonts-intl-japanese

script:
    - sudo fc-cache -v
    - cd TonNurakoTest
    - nuget restore
    - msbuild /p:Configuration=Debug TonNurakoTest.sln
    - ./headless.sh
