language: csharp
solution: TonNurako.sln

install:
    - sudo apt-get -qq update
    - sudo apt-get -qq install libmotif-dev libxmu-dev libxt-dev libfontconfig1-dev xvfb

script:
    - cd TonNurakoTest
    - nuget restore
    - msbuild /p:Configuration=Debug TonNurakoTest.sln
    - ./headless.sh
