//
// ﾄﾝﾇﾗｺ
// 
// Widget
//
namespace TonNurako.Events
{
    /// <summary>
    /// 
    /// </summary>
    public enum CallReason {
        ACTIVATE = Native.Motif.Constant.XmCR_ACTIVATE,
        APPLY = Native.Motif.Constant.XmCR_APPLY,
        ARM = Native.Motif.Constant.XmCR_ARM,
        BROWSE_SELECT = Native.Motif.Constant.XmCR_BROWSE_SELECT,
        CANCEL = Native.Motif.Constant.XmCR_CANCEL,
        CASCADING = Native.Motif.Constant.XmCR_CASCADING,
        CLIPBOARD_DATA_DELETE = Native.Motif.Constant.XmCR_CLIPBOARD_DATA_DELETE,
        CLIPBOARD_DATA_REQUEST = Native.Motif.Constant.XmCR_CLIPBOARD_DATA_REQUEST,
        COLLAPSED = Native.Motif.Constant.XmCR_COLLAPSED,
        COMMAND_CHANGED = Native.Motif.Constant.XmCR_COMMAND_CHANGED,
        COMMAND_ENTERED = Native.Motif.Constant.XmCR_COMMAND_ENTERED,
        CREATE = Native.Motif.Constant.XmCR_CREATE,
        DECREMENT = Native.Motif.Constant.XmCR_DECREMENT,
        DEFAULT_ACTION = Native.Motif.Constant.XmCR_DEFAULT_ACTION,
        DISARM = Native.Motif.Constant.XmCR_DISARM,
        DRAG = Native.Motif.Constant.XmCR_DRAG,
        DRAG_DROP_FINISH = Native.Motif.Constant.XmCR_DRAG_DROP_FINISH,
        DRAG_MOTION = Native.Motif.Constant.XmCR_DRAG_MOTION,
        DRAG_START = Native.Motif.Constant.XmCR_DRAG_START,
        DROP_FINISH = Native.Motif.Constant.XmCR_DROP_FINISH,
        DROP_MESSAGE = Native.Motif.Constant.XmCR_DROP_MESSAGE,
        DROP_SITE_ENTER = Native.Motif.Constant.XmCR_DROP_SITE_ENTER,
        DROP_SITE_ENTER_MESSAGE = Native.Motif.Constant.XmCR_DROP_SITE_ENTER_MESSAGE,
        DROP_SITE_LEAVE = Native.Motif.Constant.XmCR_DROP_SITE_LEAVE,
        DROP_SITE_LEAVE_MESSAGE = Native.Motif.Constant.XmCR_DROP_SITE_LEAVE_MESSAGE,
        DROP_SITE_MOTION_MESSAGE = Native.Motif.Constant.XmCR_DROP_SITE_MOTION_MESSAGE,
        DROP_START = Native.Motif.Constant.XmCR_DROP_START,
        END_JOB = Native.Motif.Constant.XmCR_END_JOB,
        ENTER_CHILD = Native.Motif.Constant.XmCR_ENTER_CHILD,
        EXECUTE = Native.Motif.Constant.XmCR_EXECUTE,
        EXPANDED = Native.Motif.Constant.XmCR_EXPANDED,
        EXPOSE = Native.Motif.Constant.XmCR_EXPOSE,
        EXTENDED_SELECT = Native.Motif.Constant.XmCR_EXTENDED_SELECT,
        FOCUS = Native.Motif.Constant.XmCR_FOCUS,
        FOCUS_MOVED = Native.Motif.Constant.XmCR_FOCUS_MOVED,
        GAIN_PRIMARY = Native.Motif.Constant.XmCR_GAIN_PRIMARY,
        HELP = Native.Motif.Constant.XmCR_HELP,
        INCREMENT = Native.Motif.Constant.XmCR_INCREMENT,
        INPUT = Native.Motif.Constant.XmCR_INPUT,
        LEAVE_CHILD = Native.Motif.Constant.XmCR_LEAVE_CHILD,
        LOSE_PRIMARY = Native.Motif.Constant.XmCR_LOSE_PRIMARY,
        LOSING_FOCUS = Native.Motif.Constant.XmCR_LOSING_FOCUS,
        MAJOR_TAB = Native.Motif.Constant.XmCR_MAJOR_TAB,
        MAP = Native.Motif.Constant.XmCR_MAP,
        MINOR_TAB = Native.Motif.Constant.XmCR_MINOR_TAB,
        MODIFYING_TEXT_VALUE = Native.Motif.Constant.XmCR_MODIFYING_TEXT_VALUE,
        MOVING_INSERT_CURSOR = Native.Motif.Constant.XmCR_MOVING_INSERT_CURSOR,
        MULTIPLE_SELECT = Native.Motif.Constant.XmCR_MULTIPLE_SELECT,
        NONE = Native.Motif.Constant.XmCR_NONE,
        NO_FONT = Native.Motif.Constant.XmCR_NO_FONT,
        NO_MATCH = Native.Motif.Constant.XmCR_NO_MATCH,
        NO_RENDITION = Native.Motif.Constant.XmCR_NO_RENDITION,
        OBSCURED_TRAVERSAL = Native.Motif.Constant.XmCR_OBSCURED_TRAVERSAL,
        OK = Native.Motif.Constant.XmCR_OK,
        OPERATION_CHANGED = Native.Motif.Constant.XmCR_OPERATION_CHANGED,
        PAGE_DECREMENT = Native.Motif.Constant.XmCR_PAGE_DECREMENT,
        PAGE_INCREMENT = Native.Motif.Constant.XmCR_PAGE_INCREMENT,
        PAGE_SCROLLER_DECREMENT = Native.Motif.Constant.XmCR_PAGE_SCROLLER_DECREMENT,
        PAGE_SCROLLER_INCREMENT = Native.Motif.Constant.XmCR_PAGE_SCROLLER_INCREMENT,
        PAGE_SETUP = Native.Motif.Constant.XmCR_PAGE_SETUP,
        PDM_CANCEL = Native.Motif.Constant.XmCR_PDM_CANCEL,
        PDM_EXIT_ERROR = Native.Motif.Constant.XmCR_PDM_EXIT_ERROR,
        PDM_NONE = Native.Motif.Constant.XmCR_PDM_NONE,
        PDM_OK = Native.Motif.Constant.XmCR_PDM_OK,
        PDM_START_ERROR = Native.Motif.Constant.XmCR_PDM_START_ERROR,
        PDM_START_PXAUTH = Native.Motif.Constant.XmCR_PDM_START_PXAUTH,
        PDM_START_VXAUTH = Native.Motif.Constant.XmCR_PDM_START_VXAUTH,
        PDM_UP = Native.Motif.Constant.XmCR_PDM_UP,
        POST = Native.Motif.Constant.XmCR_POST,
        PROTOCOLS = Native.Motif.Constant.XmCR_PROTOCOLS,
        REPOST = Native.Motif.Constant.XmCR_REPOST,
        RESIZE = Native.Motif.Constant.XmCR_RESIZE,
        SELECT = Native.Motif.Constant.XmCR_SELECT,
        SINGLE_SELECT = Native.Motif.Constant.XmCR_SINGLE_SELECT,
        SPIN_FIRST = Native.Motif.Constant.XmCR_SPIN_FIRST,
        SPIN_LAST = Native.Motif.Constant.XmCR_SPIN_LAST,
        SPIN_NEXT = Native.Motif.Constant.XmCR_SPIN_NEXT,
        SPIN_PRIOR = Native.Motif.Constant.XmCR_SPIN_PRIOR,
        START_JOB = Native.Motif.Constant.XmCR_START_JOB,
        TAB_SELECTED = Native.Motif.Constant.XmCR_TAB_SELECTED,
        TAB_UNSELECTED = Native.Motif.Constant.XmCR_TAB_UNSELECTED,
        TEAR_OFF_ACTIVATE = Native.Motif.Constant.XmCR_TEAR_OFF_ACTIVATE,
        TEAR_OFF_DEACTIVATE = Native.Motif.Constant.XmCR_TEAR_OFF_DEACTIVATE,
        TOP_LEVEL_ENTER = Native.Motif.Constant.XmCR_TOP_LEVEL_ENTER,
        TOP_LEVEL_LEAVE = Native.Motif.Constant.XmCR_TOP_LEVEL_LEAVE,
        TO_BOTTOM = Native.Motif.Constant.XmCR_TO_BOTTOM,
        TO_TOP = Native.Motif.Constant.XmCR_TO_TOP,
        UNMAP = Native.Motif.Constant.XmCR_UNMAP,
        UPDATE_SHELL = Native.Motif.Constant.XmCR_UPDATE_SHELL,
        UPDATE_TEXT = Native.Motif.Constant.XmCR_UPDATE_TEXT,
        VALUE_CHANGED = Native.Motif.Constant.XmCR_VALUE_CHANGED,
        VERIFY_TEXT = Native.Motif.Constant.XmCR_VERIFY_TEXT,
        VERIFY_TEXT_FAILED = Native.Motif.Constant.XmCR_VERIFY_TEXT_FAILED,
        WM_PROTOCOLS = Native.Motif.Constant.XmCR_WM_PROTOCOLS
    }
}
